@startuml

left to right direction

skinparam headerAlignment left

skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Customer" as Customer

rectangle "Travel Trove System" {

    usecase "1. Sign up for an Account"
    usecase "2. Set up Profile"

    usecase "3. Browse packages"
    usecase "4. Book a package"
    usecase "5. Pay for a tour package"
    usecase "6. Manage travelers for booking"
    usecase "7. Add a Review to a Package"
    usecase "8. Subscribe to notifications"
}

"1. Sign up for an Account" <.. "2. Set up Profile" : <<extend>>

"3. Browse packages" <.. "4. Book a package" : <<extend>>
"3. Browse packages" <.. "8. Subscribe to notifications" : <<extend>>

"4. Book a package" ..> "5. Pay for a tour package" : <<include>>
"4. Book a package" <.. "6. Manage travelers for booking" : <<extend>>
"4. Book a package" <.. "7. Add a Review to a Package" : <<extend>>

Customer -- "1. Sign up for an Account"
Customer -- "3. Browse packages"

@enduml
