@startuml
skinparam linetype polyline
skinparam monochrome true
skinparam entity {
    BackgroundColor #DDEEFF
    BorderColor #3366CC
    FontColor Black
}

' Entities
entity "Users" as Users {
    + _id: ObjectId
    --
    userId: String <<Unique>>
    firstName: String
    lastName: String
    email: String <<Unique>>
    password: String
    phoneNumber: String
    role: Enum [Admin, Customer, Employee]
}

entity "Travelers" as Travelers {
    + _id: ObjectId
    --
    travelerId: String <<Unique>>
    seq: Integer
    firstName: String
    lastName: String
    addressLine1: String
    addressLine2: String
    city: String
    state: String
    email: String
    countryId: String <<FK>>
}

entity "TourPackages" as TourPackages {
    + _id: ObjectId
    --
    packageId: String <<Unique>>
    name: String
    description: String
    startDate: DateTime
    endDate: DateTime
    priceForOne: Decimal
    priceForTwo: Decimal
    priceForThree: Decimal
    airportId: String <<FK>>
    tourId: String <<FK>>
}

entity "Bookings" as Bookings {
    + _id: ObjectId
    --
    bookingId: String <<Unique>>
    userId: String <<FK>>
    packageId: String <<FK>>
    refundId: String <<FK>>
    bookingDate: DateTime
    totalAmount: Decimal
    status: String
}

entity "Traveler" as Traveler {
    + _id: ObjectId
    --
    travelerId: String <<Unique>>
    seq: Integer
    firstName: String
    lastName: String
    addressLine1: String
    addressLine2: String
    city: String
    state: String
    email: String
    countryId: String <<FK>>
    userId: String <<FK>> <<Optional>>
}

entity "Refunds" as Refunds {
    + _id: ObjectId
    --
    refundId: String <<Unique>>
    bookingId: String <<FK>>
    userID: String <<FK>>
    refundedAmount: Decimal
    totalTransactionAmount: Decimal
}

entity "Payments" as Payments {
    + _id: ObjectId
    --
    paymentId: String <<Unique>>
    bookingId: String <<FK>>
    stripePaymentId: String <<Unique>>
    paymentDate: DateTime
    amount: Decimal
    status: String
}

entity "Reviews" as Reviews {
    + _id: ObjectId
    --
    reviewId: String <<Unique>>
    userId: String <<FK>>
    packageId: String <<FK>>
    bookingId: String <<FK>>
    rating: Integer
    comment: String
    reviewDate: DateTime
}

entity "Hotels" as Hotels {
    + _id: ObjectId
    --
    hotelId: String <<Unique>>
    name: String
    cityId: String <<FK>>
    countryId: String <<FK>>
    address: String
    hotelUrl: String
}

entity "Airports" as Airports {
    + _id: ObjectId
    --
    airportId: String <<Unique>>
    name: String
    cityId: String <<FK>>
}

entity "Cities" as Cities {
    + _id: ObjectId
    --
    cityId: String <<Unique>>
    name: String
    countryId: String <<FK>>
}

entity "Countries" as Countries {
    + _id: ObjectId
    --
    countryId: String <<Unique>>
    name: String
    imagePath: String
}

entity "Events" as Events {
    + _id: ObjectId
    --
    eventId: String <<Unique>>
    title: String
    description: String
    cityId: String <<FK>>
}

entity "TourEvents" as TourEvents {
    + _id: ObjectId
    --
    tourEventId: String <<Unique>>
    seq: Integer
    seqDesc: String
    tourId: String <<FK>>
    eventId: String <<FK>>
    hotelId: String <<FK>>
}

' Relationships
Users ||--o{ Bookings : "1:N"
Users ||--o{ Reviews : "1:N"
TourPackages ||--o{ Bookings : "1:N"
TourPackages ||--o{ Reviews : "1:N"
Bookings ||--|| Payments : "1:1"
Cities ||--o{ Hotels : "1:N"
Cities ||--o{ Airports : "1:N"
Countries ||--o{ Cities : "1:N"
Cities ||--o{ Events : "1:N"
TourPackages ||--o{ Airports : "1:1"
TourPackages ||--o{ TourEvents : "1:N"
TourEvents ||--o{ Events : "1:N"
TourEvents ||--o{ Hotels : "1:M"
"Bookings" ||--o{ "Refunds" : "1:N"
Travelers ||--o{ Countries : "1:1"
Traveler }o--o| Users : "Optional"
Traveler ||--o{ Bookings : "1:N"

@enduml
