@startuml

left to right direction

' Add a header with left alignment
header
Dar El Salam
endheader

' Align the header text to the left
skinparam headerAlignment left

' Custom skin parameters for use cases
skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Customer" as Customer

rectangle "Travel Trove System" {

    usecase "Sign up for an Account"
    usecase "Set up Profile"
    usecase "View Account"
    usecase "Edit Account"
    usecase "View Profile"
    usecase "Modify Profile Information"

    usecase "Browse tour packages"
    usecase "Filter search result"
    usecase "Subscribe to notifications"

    usecase "Book a tour package"
    usecase "Pay for a tour"

    usecase "Cancel a tour"
    usecase "Request a refund"

    usecase "View Travelers"
    usecase "View Traveler Details"
    usecase "Add a Traveler"
    usecase "Edit a Traveler"
    usecase "Assign a Traveler to booking"
    usecase "Remove a Traveler from booking"

    usecase "Access package bookings"
}

"Sign up for an Account" <.. "Set up Profile" : <<extend>>
"Sign up for an Account" <.. "View Account" : <<extend>>
"View Account" <.. "Edit Account" : <<extend>>
"Browse tour packages" <.. "Book a tour package" : <<extend>>
"Browse tour packages" <.. "Subscribe to notifications" : <<extend>>
"Book a tour package" <.. "Filter search result" : <<extend>>
"Book a tour package" <.. "Pay for a tour" : <<include>>
"Cancel a tour" <.. "Request a refund" : <<extend>>
"Sign up for an Account" <.. "View Profile" : <<extend>>
"View Profile" <.. "Modify Profile Information" : <<extend>>
"View Profile" <.. "Set up Profile" : <<extend>>
"Access package bookings" <.. "View Travelers" : <<extend>>
"Access package bookings" <.. "View Traveler Details" : <<extend>>
"Access package bookings" <.. "Add a Traveler" : <<extend>>
"Access package bookings" <.. "Edit a Traveler" : <<extend>>
"Access package bookings" <.. "Remove a Traveler from booking" : <<extend>>
"Book a tour package" <.. "View Travelers" : <<extend>>"
"Book a tour package" <.. "View Traveler Details" : <<extend>>"
"Book a tour package" <.. "Remove a Traveler from booking" : <<extend>>"
"Book a tour package" <.. "Assign a Traveler to booking" : <<extend>>"

Customer -- "Sign up for an Account"
Customer -- "Browse tour packages"
Customer -- "Access package bookings"
Customer -- "Cancel a tour"

@enduml