@startuml
left to right direction

' Add a header with left alignment
header
Dar El Salam
endheader

' Custom skin parameters for use cases
skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Dar El Salam's Employee" as Employee

rectangle "Travel Trove System" {

    usecase "Browse tour packages"
    usecase "Add tour package"
    usecase "Modify tour package"
    usecase "Filter search result"
    usecase "Custom notification"
    usecase "Manage events"
    usecase "Manage tours"
    usecase "Manage countries"
    usecase "Manage cities"
    usecase "Manage tour events"
    usecase "View Account"
    usecase "Edit Account"
    usecase "Manage hotels"
    usecase "Manage airports"

    usecase "Access package bookings"
    usecase "Assign a Traveler to booking"
    usecase "Remove a Traveler from booking"
    usecase "View Travelers"
    usecase "View Traveler Details"
}
Employee -- "Browse tour packages"
Employee -- "Manage events"
Employee -- "Manage tours"
Employee -- "Manage countries"
Employee -- "Manage cities"
Employee -- "View Account"
Employee -- "Manage hotels"
Employee -- "Manage airports"
Employee -- "Access package bookings"

"Browse tour packages" <.. "Filter search result" : <<extend>>
"Browse tour packages" <.. "Add tour package" : <<extend>>
"Browse tour packages" <.. "Modify tour package" : <<extend>>
"Modify tour package" <.. "Custom notification" : <<extend>>
"Modify tour package" <.. "Filter search result" : <<extend>>
"Manage tours" <.. "Manage tour events" : <<extend>>
"View Account" <.. "Edit Account" : <<extend>>
"Access package bookings" <.. "Assign a Traveler to booking" : <<extend>>
"Access package bookings" <.. "Remove a Traveler from booking" : <<extend>>
"Access package bookings" <.. "View Travelers" : <<extend>>
"View Travelers" <.. "View Traveler Details" : <<extend>>

@enduml