@startuml
scale 1
left to right direction

header
Dar El Salam
endheader

skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Dar El Salam's Admin" as Admin

rectangle "Travel Trove System" {

    usecase "Manage user accounts"
    usecase "Control Roles"
    usecase "Generate report"
    usecase "Remove a tour package"

}

"Manage user accounts" ..> "Control Roles" : <<include>>
Admin <|-- Employee
Admin -- "Manage user accounts"
Admin -- "Generate report"
Admin -- "Remove a tour package"


@enduml