@startuml
[*] --> TourSelection : selectTourPackage()

TourSelection -down-> PaymentPending : proceedToPayment()

PaymentPending -right-> BookingConfirmed : paymentConfirmed()
PaymentPending -down-> RetryPayment1 : paymentFailed()

RetryPayment1 -up-> PaymentPending : attemptPayment()
RetryPayment1 -down-> RetryPayment2 : paymentFailed()

RetryPayment2 -up-> PaymentPending : attemptPayment()
RetryPayment2 -down-> BookingFailed : maxRetriesReached()

BookingFailed --> [*]
BookingConfirmed --> [*]

@enduml
