server:
  port: 8080

logging:
  level:
    root: INFO
    com.be-traveltrove: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.traveltrove.betraveltrove.config.security: DEBUG

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: traveltrovedb
      username: root
      password: password
      authentication-database: admin

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

okta:
  oauth2:
    issuer: https://dev-traveltrove.ca.auth0.com/
    audience: https://api.traveltrove.com

---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongo
      port: 27017
      database: traveltrovedb
      username: root
      password: password
      authentication-database: admin