spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: testdb
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        enabled: false

frontend:
  domain: ${FRONTEND_DOMAIN}

auth0:
  domain: dev-traveltrove.ca.auth0.com
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://dev-traveltrove.ca.auth0.com/api/v2/

okta:
  oauth2:
    issuer: https://dev-traveltrove.ca.auth0.com/
    audience: https://api.traveltrove.com

logging:
  level:
    root: DEBUG
    com.be-traveltrove: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
