server:
  port: 8080

logging:
  level:
    root: INFO
    com.be-traveltrove: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.traveltrove.betraveltrove.config.security: DEBUG

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: traveltrovedb
      username: root
      password: password
      authentication-database: admin

  config:
    import: "optional:classpath:.env"

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    audience: ${AUTH0_AUDIENCE}

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_MANAGEMENT_API_AUDIENCE}

---

spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongo
      port: 27017
      database: traveltrovedb
      username: root
      password: password
      authentication-database: admin
