@startuml
left to right direction

skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Dar El Salam's Employee" as Employee

rectangle "Travel Trove System" {

    usecase "1. Manage tours"
    usecase "2. Browse packages"
    usecase "3. Add package"
    usecase "4. Modify package"
    usecase "5. Custom notification"
    usecase "6. View package bookings"
    usecase "7. View Travelers"
    usecase "8. Filter search result"
    usecase "9. Manage events"
    usecase "10. Manage countries"
    usecase "11. Manage cities"
    usecase "12. Manage tour events"
    usecase "13. Manage hotels"
    usecase "14. Manage airports"
    usecase "15. View Package Reviews"
}

Employee -- "1. Manage tours"
Employee -- "9. Manage events"
Employee -- "1. Manage tours"
Employee -- "10. Manage countries"
Employee -- "11. Manage cities"
Employee -- "13. Manage hotels"
Employee -- "14. Manage airports"

"1. Manage tours" <.. "12. Manage tour events" : <<extend>>
"1. Manage tours" <.. "2. Browse packages" : <<extend>>
"2. Browse packages" <.. "8. Filter search result" : <<extend>>
"2. Browse packages" <.. "3. Add package" : <<extend>>
"2. Browse packages" <.. "4. Modify package" : <<extend>>
"2. Browse packages" <.. "6. View package bookings" : <<extend>>
"2. Browse packages" <.. "15. View Package Reviews" : <<extend>>
"4. Modify package" <.. "5. Custom notification" : <<extend>>
"6. View package bookings" <.. "7. View Travelers" : <<extend>>

@enduml