@startuml

left to right direction

skinparam usecase {
    BackgroundColor lightblue
    BorderColor DarkSlateGray
    ArrowColor Black
}

actor "Dar El Salam's Admin" as Admin

rectangle "Travel Trove System" {

    usecase "1. Manage user accounts"
    usecase "2. Manage Roles"
    usecase "3. Filter by Roles"
    usecase "4. Generate reports"
    usecase "5. Cancel a package"
    usecase "6. Remove a tour"

}

"1. Manage user accounts" <.. "2. Manage Roles" : <<extends>>
"1. Manage user accounts" <.. "3. Filter by Roles" : <<extends>>
Admin <|-- Employee
Admin -- "1. Manage user accounts"
Admin -- "4. Generate reports"
Admin -- "5. Cancel a package"
Admin -- "6. Remove a tour"


@enduml