@startuml
title Package Subdomain Design Class Diagram

package "packagesubdomain" {
    package "businesslayer" {
        interface PackageService {
            + getAllPackages() : Flux<PackageResponseModel>
            + getPackageById(packageId: String) : Mono<PackageResponseModel>
            + addPackage(package: PackageRequestModel) : Mono<PackageResponseModel>
            + updatePackage(packageId: String, packageRequestModel: PackageRequestModel) : Mono<PackageResponseModel>
            + deletePackage(packageId: String) : Mono<Void>
            + decreaseAvailableSeats(packageId: String, quantity: Integer) : Mono<PackageResponseModel>
            + increaseAvailableSeats(packageId: String, quantity: Integer) : Mono<PackageResponseModel>
            + sendLimitedSpotsNotification(packageId: String) : Mono<Void>
            + sendPackageUpdateNotification(packageId: String) : Mono<Void>
        }

        class PackageServiceImpl {
            - packageRepository: PackageRepository
            + getAllPackages() : Flux<PackageResponseModel>
            + getPackageById(packageId: String) : Mono<PackageResponseModel>
            + addPackage(package: PackageRequestModel) : Mono<PackageResponseModel>
            + updatePackage(packageId: String, packageRequestModel: PackageRequestModel) : Mono<PackageResponseModel>
            + deletePackage(packageId: String) : Mono<Void>
            + decreaseAvailableSeats(packageId: String, quantity: Integer) : Mono<PackageResponseModel>
            + increaseAvailableSeats(packageId: String, quantity: Integer) : Mono<PackageResponseModel>
            + sendLimitedSpotsNotification(packageId: String) : Mono<Void>
            + sendPackageUpdateNotification(packageId: String) : Mono<Void>
        }
    }

    package "dataaccesslayer" {
        class Package {
            + _id: ObjectId
            + packageId: String
            + name: String
            + description: String
            + startDate: DateTime
            + endDate: DateTime
            + priceForOne: Decimal
            + priceForTwo: Decimal
            + priceForThree: Decimal
            + airportId: String
            + tourId: String
            + availableSeats: Integer
            + totalSeats: Integer
        }

        interface PackageRepository extends ReactiveMongoRepository {
            + findPackageByPackageId(packageId: String) : Mono<Package>
            + findAll() : Flux<Package>
            + findPackagesByTourId(tourId: String) : Flux<Package>
        }
    }

    package "presentationlayer" {
        class PackageRequestModel {
            + name: String
            + description: String
            + startDate: DateTime
            + endDate: DateTime
            + priceForOne: Decimal
            + priceForTwo: Decimal
            + priceForThree: Decimal
            + airportId: String
            + tourId: String
            + totalSeats: Integer
        }

        class PackageResponseModel {
            + packageId: String
            + name: String
            + description: String
            + startDate: DateTime
            + endDate: DateTime
            + priceForOne: Decimal
            + priceForTwo: Decimal
            + priceForThree: Decimal
            + airportId: String
            + tourId: String
            + availableSeats: Integer
            + totalSeats: Integer
        }

        class PackageController {
            - packageService: PackageService
            + getAllPackages() : Flux<PackageResponseModel>
            + getPackageById(packageId: String) : Mono<ResponseEntity<PackageResponseModel>>
            + addPackage(packageRequestModel: PackageRequestModel) : Mono<PackageResponseModel>
            + updatePackage(packageId: String, packageRequestModel: PackageRequestModel) : Mono<ResponseEntity<PackageResponseModel>>
            + deletePackage(packageId: String) : Mono<Void>
            + decreaseAvailableSeats(packageId: String, quantity: Integer) : Mono<PackageResponseModel>
            + increaseAvailableSeats(packageId: String, quantity: Integer) : Mono<PackageResponseModel>
            + sendLimitedSpotsNotification(packageId: String) : Mono<Void>
            + sendPackageUpdateNotification(packageId: String) : Mono<Void>
        }
    }

    package "utils" {
        class EntityModelUtil_package {
            + toPackageResponseModel(package: Package) : PackageResponseModel
            + toPackageEntity(packageRequestModel: PackageRequestModel) : Package
            + generateUUIDString() : String
        }
    }

    PackageServiceImpl -down-|> PackageService
    PackageServiceImpl -down-> PackageRepository
    PackageController -down-> PackageService
    PackageController -down-> PackageRequestModel
    PackageController -down-> PackageResponseModel
    PackageServiceImpl -down-> Package
    PackageServiceImpl -down-> PackageRequestModel
    PackageServiceImpl -down-> PackageResponseModel
    EntityModelUtil_package -up-^ Package
    EntityModelUtil_package -up-^ PackageRequestModel
    EntityModelUtil_package -up-^ PackageResponseModel
}

@enduml
