name: CI for TravelTrove

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permissions to gradlew
        working-directory: be-traveltrove
        run: chmod +x gradlew

      - name: Set up environment variables
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATA_MONGODB_DATABASE: testdb
          SPRING_DATA_MONGODB_HOST: localhost
          SPRING_DATA_MONGODB_PORT: 27017
          SERVER_PORT: 8080
          AUTH0_CLIENT_ID: test-client-id
          AUTH0_CLIENT_SECRET: test-client-secret
          AUTH0_AUDIENCE: https://dev-traveltrove.ca.auth0.com/api/v2/
        run: echo "Environment variables set"

      - name: Build and test backend
        working-directory: be-traveltrove
        run: ./gradlew clean build -Dspring.profiles.active=test

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: fe-traveltrove
        run: npm install

      - name: Run Playwright tests
        working-directory: fe-traveltrove
        run: npm run test:tests
