name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      FRONTEND_DOMAIN: ${{ secrets.FRONTEND_DOMAIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: fe-traveltrove/package-lock.json

      # Create the .env file for the frontend
      - name: Create .env file for frontend
        run: |
          echo "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}" > fe-traveltrove/.env
          echo "AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}" >> fe-traveltrove/.env
          echo "FRONTEND_DOMAIN=${FRONTEND_DOMAIN}" >> fe-traveltrove/.env
        shell: bash

      # Install backend dependencies
      - name: Install backend dependencies
        run: npm install --legacy-peer-deps
        working-directory: be-traveltrove

      # Start backend server
      - name: Start backend server
        run: |
          npm start &
          sleep 5
        working-directory: be-traveltrove

      # Install Docker Compose
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Build and start Docker containers
      - name: Build and start Docker containers
        run: docker-compose -f docker-compose.yml up -d --build

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        working-directory: fe-traveltrove

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: fe-traveltrove

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: fe-traveltrove

      # Upload Playwright test report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: fe-traveltrove/playwright-report/
          retention-days: 30

      # Stop Docker containers
      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down

      # Stop backend server
      - name: Stop backend server
        run: |
          pkill -f npm || true
