name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: fe-traveltrove/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: fe-traveltrove

      # Step 4: Verify directory structure before ESLint
      - name: Debug repository structure
        run: ls -R
        working-directory: fe-traveltrove

      - name: Run ESLint in batches
        run: |
          npx eslint src/pages --ext ts,tsx --cache --report-unused-disable-directives
          npx eslint src/features --ext ts,tsx --cache --report-unused-disable-directives
          npx eslint src/layouts --ext ts,tsx --cache --report-unused-disable-directives
        working-directory: fe-traveltrove


      # Step 6: Build the project
      - name: Run build to ensure no build errors
        run: npm run build
        working-directory: fe-traveltrove
