name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: fe-traveltrove/package-lock.json

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        run: npm ci
        working-directory: be-traveltrove

      # Step 4: Start backend server
      - name: Start backend server
        run: |
          npm start &
          sleep 5 # Wait for the backend to start
        working-directory: be-traveltrove

      # Step 5: Install Docker (if required) and start services
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start Docker containers
        run: docker-compose -f docker-compose.yml up -d --build

      # Step 6: Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci
        working-directory: fe-traveltrove

      # Step 7: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: fe-traveltrove

      # Step 8: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: fe-traveltrove

      # Step 9: Upload Playwright test report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: fe-traveltrove/playwright-report/
          retention-days: 30

      # Step 10: Stop Docker containers
      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down

      # Step 11: Stop backend server
      - name: Stop backend server
        run: |
          pkill -f npm || true
